version: "3.8"
services:
  data_loader:
    build: .
    volumes:
    - "./data:/data"
    ports:
      - "5000:5000"
      - "25000:25000"
    environment:
    - COVIDDI_HOME=/data/coviddi
    - INFLUX_HOST=influxdb
    - INFLUX_PORT=8086
    - INFLUXDB_ORG=coviddi
    - INFLUXDB_TOKEN=antani22
  influxdb:
    image: influxdb:2.0.9
    ports:
    - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dataload
      - DOCKER_INFLUXDB_INIT_PASSWORD=antani22
      - DOCKER_INFLUXDB_INIT_ORG=coviddi
      - DOCKER_INFLUXDB_INIT_BUCKET=coviddi
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=antani22
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2

volumes:
  influx_data:
  influx_config: